Adapté de https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

# Qu'est-ce que PyTorch?

-  Une librairie pouvant remplacer **NumPy** et permettant une **accélération GPU**
-  Une plateforme pour la **recherche en Deep Learning** offrant un maximum de **flexibilité et de rapidité**

## Tenseurs (`Tensor`)

Les tenseurs sont similaires aux `ndarray` de NumPy, et peuvent être utilisés sur GPU.

In [17]:
import torch

Construisons une matrice 5x3 non-initialisée:

In [18]:
x = torch.empty(5, 3)
print(x)

tensor([[ 1.4426e-36,  0.0000e+00,  1.4714e-43],
        [ 1.5414e-43,  1.6255e-43,  5.6052e-44],
        [ 1.6816e-43,  1.2752e-43,  8.1275e-44],
        [ 6.1657e-44,  4.4842e-44,  6.8664e-44],
        [ 1.3032e-43,  5.7453e-44, -5.8867e+13]])


Construisons une matrice 5x3 de nombre aléatoires (entre 0 et 1):

In [19]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5574, 0.4912, 0.8186],
        [0.0535, 0.7244, 0.1928],
        [0.4438, 0.4214, 0.9664],
        [0.8492, 0.8615, 0.0926],
        [0.9805, 0.8370, 0.2549]])


Construisons une matrice remplie de zéros, et de type `long`:

In [20]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construisons une matrice à partir de données:

In [21]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [22]:
x = torch.tensor([[1, 0], [0, 1]])
print(x)

tensor([[1, 0],
        [0, 1]])


Note: Les fonctions `torch.*_like(x)` fonctionnent de la même façon qu'avec NumPy (e.g. `zeros_like(x)`)

Affichons les dimensions du tenseur:

In [23]:
print(x.size())
print(x.shape)

torch.Size([2, 2])
torch.Size([2, 2])


Note: `torch.Size` est une sous-classe de `tuple`.

Vous pouvez aussi obtenir la taille d'une seule dimension d'un coup:

In [24]:
print(x.size(0))

2


## Opérations

Les opérations sur les tenseurs peuvent être faites avec différentes syntaxes. Regardons l'exemple de l'addition.

**Addition: syntaxe 1**

In [25]:
x = torch.rand(5, 3)
y = torch.ones_like(x)

somme = x + y
print(somme)

tensor([[1.2994, 1.9858, 1.0286],
        [1.8003, 1.3529, 1.4085],
        [1.2886, 1.0708, 1.3344],
        [1.6652, 1.9294, 1.8664],
        [1.6598, 1.7874, 1.6014]])


**Addition: syntaxe 2**

In [26]:
somme = torch.add(x, y)
print(somme)

tensor([[1.2994, 1.9858, 1.0286],
        [1.8003, 1.3529, 1.4085],
        [1.2886, 1.0708, 1.3344],
        [1.6652, 1.9294, 1.8664],
        [1.6598, 1.7874, 1.6014]])


**Addition: fournir un tenseur de destination**

In [27]:
somme = torch.empty(5, 3)
torch.add(x, y, out=somme)
print(somme)

tensor([[1.2994, 1.9858, 1.0286],
        [1.8003, 1.3529, 1.4085],
        [1.2886, 1.0708, 1.3344],
        [1.6652, 1.9294, 1.8664],
        [1.6598, 1.7874, 1.6014]])


**Addition: "in-place"**

In [28]:
y.add_(x)  # équivalent à torch.add(x, y, out=y)
print(y)

tensor([[1.2994, 1.9858, 1.0286],
        [1.8003, 1.3529, 1.4085],
        [1.2886, 1.0708, 1.3344],
        [1.6652, 1.9294, 1.8664],
        [1.6598, 1.7874, 1.6014]])


Note: les méthodes opérant "in-place" ont le suffixe `_`. Par exemple, `x.t_()` transpose `x`, alors que `x.t()` retourne un nouveau tenseur contenant `x` transposé.

**Indiçage**

Vous pouvez utiliser la même syntaxe qu'avec NumPy, même pour les cas complexes!

In [29]:
print(x[:, 1])
print(x[:, np.newaxis, 1])

tensor([0.9858, 0.3529, 0.0708, 0.9294, 0.7874])


NameError: name 'np' is not defined

`torch.reshape` est équivalent à `numpy.reshape`. Cependant, `torch.view` est plus souvent utilisée (mais ne fonctionne que lorsqu'une les valeurs n'ont pas à être copiées):

In [ ]:
x = torch.randn(4, 4)
print(x.size())

y = x.view(16)
print(y.size())

z = x.view(-1, 8)  # -1 permet d'inférer automatiquement les autres dimensions
print(z.size())

Si vous avez un tenseur contenant un seul élément, utilisez `.item()` pour obtenir la valeur sous forme de nombre Python:

In [ ]:
x = torch.randn(4).mean()
print(x)
print(x.item())

**À voir plus tard:** 100+ opérations, includant transposée, indiçage, _slicing_, algèbre linéaire, nombres aléatoires, etc. : https://pytorch.org/docs/torch

# Interopérabilité avec NumPy

La conversion d'un tenseur PyTorch en un NumPy array, et vice versa, est simple comme bonjour.

Le tenseur et le NumPy array utiliseront le même espace mémoire (si le tenseur n'est pas sur GPU); modifier l'un modifie l'autre du même coup.

## Conversion PyTorch --> NumPy

In [ ]:
a = torch.ones(5)
print(type(a))
print(a)

In [ ]:
b = a.numpy()
print(type(b))
print(b)

Modifions le tenseur et observons le changement dans le NumPy array:

In [ ]:
a.add_(1)
print(a)
print(b)

## Conversion NumPy --> PyTorch

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


# Placer un tenseur sur GPU

Les tenseurs peuvent être placés sur un appareil (`torch.device`) avec la méthode `.to`:

In [ ]:
assert torch.cuda.device_count() > 0, "On va avoir besoin d'un GPU"

device = torch.device("cuda")
x = torch.rand(2, 2, device=device)    # créer un tenseur directement sur GPU
y = torch.ones_like(x)
x = x.to(device)                       # placer un tenseur existant sur GPU
z = x + y
print(z)
print(z.to("cpu", torch.double))       # ``.to`` peut aussi changer le type du même coup