In [113]:
import torch


# Autograd: Dérivation automatique

Grâce à `torch.autograd`, PyTorch permet d'enregistrer "on the fly" le graphe d'une suite d'opérations. Cela est utile pour calculer le gradient (dérivées partielles) d'une fonction par rapport à certains de ses paramètres.

Ce qui distingue PyTorch (au moment de son apparition), c'est qu'il fonctionne avec le principe "define-by-run"; c'est-à-dire qu'au lieu que les graphes soient compilés à l'avance comme dans TensorFlow, les graphes sont définis à mesure que le code Python est éxécuté. Cela apporte une grande flexibilité et une facilité pour le prototypage.

## Tensor

`torch.Tensor` est la classe centrale de `torch.autograd`. Pour enregistrer toutes les opérations effectuées sur un tensor, il faut mettre sont attribut `.requires_grad` à `True`.

Voyons un exemple. Supposons que nous voulons entraîner une régression linéaire de la forme `y = x @ w`:

In [114]:
x = torch.rand(2, 2)       # Données en entrée
y_true = torch.rand(2, 2)  # Données cible

Créons le vecteur de poids `w` à entraîner.

In [115]:
w = torch.rand(2, 2, requires_grad=True)
print(w)

tensor([[0.8457, 0.0999],
        [0.7537, 0.8020]], requires_grad=True)


Maintenant, effectuons une inférence:

In [116]:
y_pred = x @ w
print(y_pred)

tensor([[0.4825, 0.4847],
        [1.1672, 0.7212]], grad_fn=<MmBackward>)


`y_pred` est le résultat d'une multiplication matricielle. Il a donc un attribut `grad_fn` qui référencie la fonction utilisée:

In [117]:
print(y_pred.grad_fn)

Calculons maintenant l'erreur quadratique sur ces prédictions:

In [118]:
loss_per_element = (y_true - y_pred) ** 2
loss = loss_per_element.mean()

print(loss_per_element)
print(loss)

tensor([[0.0620, 0.0885],
        [1.1572, 0.0365]], grad_fn=<PowBackward0>)
tensor(0.3361, grad_fn=<MeanBackward1>)


## Backpropagation des gradients

Nous allons maintenant effectuer une "backpropagation" afin d'obtenir la dérivée de la loss par rapport aux paramètres:

In [119]:
loss.backward()

PyTorch parcourt le graphe et place les valeurs de dérivées dans l'attribut `.grad` des tenseurs ayant demandé le calcul du leur gradient. Affichons le gradient de l'erreur par rapport à `w`:

In [120]:
print(w.grad)

tensor([[ 0.3457,  0.0568],
        [ 0.3654, -0.0111]])


Grâce à ces dérivées partielles, nous pouvons maintenant faire une descente de gradient afin d'optimiser `w`:

In [121]:
w.data -= w.grad

Faisons maintenant une nouvelle inférence, et calculons l'erreur:

In [122]:
old_loss = loss.item()

y_pred = x @ w
loss = ((y_true - y_pred) ** 2).mean() 

print('Avant', old_loss)
print('Apres', loss.item())

Avant 0.3360506296157837
Apres 0.16193608939647675


Remarquez que l'erreur a diminué! Magie!