Adapté de https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

# Qu'est-ce que PyTorch?

-  Une librairie pouvant remplacer **NumPy** et permettant une **accélération GPU**
-  Une plateforme pour la **recherche en Deep Learning** offrant un maximum de **flexibilité et de rapidité**

## Tenseurs (`Tensor`)

Les tenseurs sont similaires aux `ndarray` de NumPy, et peuvent être utilisés sur GPU.

In [1]:
import torch

Construisons une matrice 5x3 non-initialisée:

In [ ]:
x = torch.empty(5, 3)
print(x)

Construisons une matrice 5x3 de nombre aléatoires (entre 0 et 1):

In [ ]:
x = torch.rand(5, 3)
print(x)

Construisons une matrice remplie de zéros, et de type `long`:

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

Construisons une matrice à partir de données:

In [2]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [3]:
x = torch.tensor([[1, 0], [0, 1]])
print(x)

tensor([[1, 0],
        [0, 1]])


Les fonctions `torch.*_like(x)` fonctionnent de la même façon qu'avec NumPy (e.g. `zeros_like(x)`)

Affichons les dimensions du tenseur:

In [4]:
print(x.size())

torch.Size([2, 2])


Note: `torch.Size` est une sous-classe de `tuple`.

Vous pouvez aussi obtenir la taille d'une seule dimension d'un coup:

In [5]:
print(x.size(0))

2


## Opérations

Les opérations sur les tenseurs peuvent être faites avec différentes syntaxes. Regardons l'exemple de l'addition.

**Addition: syntaxe 1**

In [7]:
x = torch.rand(5, 3)
y = torch.ones_like(x)

somme = x + y
print(somme)

tensor([[1.9622, 1.9624, 1.7386],
        [1.4057, 1.3514, 1.7441],
        [1.5940, 1.7360, 1.5939],
        [1.3558, 1.7314, 1.3920],
        [1.7844, 1.8681, 1.5147]])


**Addition: syntaxe 2**

In [8]:
somme = torch.add(x, y)
print(somme)

tensor([[1.9622, 1.9624, 1.7386],
        [1.4057, 1.3514, 1.7441],
        [1.5940, 1.7360, 1.5939],
        [1.3558, 1.7314, 1.3920],
        [1.7844, 1.8681, 1.5147]])


**Addition: fournir un tensor de destination**

In [11]:
somme = torch.empty(5, 3)
torch.add(x, y, out=somme)
print(somme)

tensor([[1.9622, 1.9624, 1.7386],
        [1.4057, 1.3514, 1.7441],
        [1.5940, 1.7360, 1.5939],
        [1.3558, 1.7314, 1.3920],
        [1.7844, 1.8681, 1.5147]])


**Addition: "in-place"**

In [12]:
y.add_(x)  # équivalent à y = y + x, mais sans allouer un tenseur intermédiaire pour y + x
print(y)

tensor([[1.9622, 1.9624, 1.7386],
        [1.4057, 1.3514, 1.7441],
        [1.5940, 1.7360, 1.5939],
        [1.3558, 1.7314, 1.3920],
        [1.7844, 1.8681, 1.5147]])


Note: les opérations opérant "in-place" ont le suffixe `_`. Par exemple, `x.t_()` transpose `x`, alors que `x.t()` retourne un nouveau tenseur contenant `x` transposé.

**Indiçage**

Vous pouvez utiliser la même syntaxe qu'avec NumPy, même pour les cas complexes!

In [13]:
print(x[:, 1])

tensor([0.9624, 0.3514, 0.7360, 0.7314, 0.8681])


`torch.reshape()` est équivalent à `numpy.reshape()`. `torch.view()` est similaire et plus souvent utilisé (mais ne fonctionne que lorsqu'une copie peut être évitée):

In [16]:
x = torch.randn(4, 4)
print(x.size())

y = x.view(16)
print(y.size())

z = x.view(-1, 8)  # -1 permet d'inférer automatiquement les autres dimensions
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


Si vous avez un tenseur contenant un seul élément, utilisez `.item()` pour obtenir la valeur sous forme de nombre Python:

In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4250])
-0.42499351501464844


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [ ]:
a = torch.ones(5)
print(a)

In [ ]:
b = a.numpy()
print(b)

See how the numpy array changed in value.



In [ ]:
a.add_(1)
print(a)
print(b)

Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!